export const groupData = [
  // Big friends networks
  [
    {
      id: 0,
      grievances: true,
      public: false,
      private: false,
      friends: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 1,
      grievances: true,
      public: false,
      private: true,
      friends: [
        0,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: ['dream'],
      nResponses: 20,
    },
    {
      id: 2,
      grievances: false,
      public: true,
      private: true,
      friends: [
        0,
        1,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 2,
    },
    {
      id: 3,
      grievances: false,
      public: true,
      private: false,
      friends: [
        0,
        1,
        2,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: ['UM'],
      nResponses: 20,
    },
    {
      id: 4,
      grievances: false,
      public: false,
      private: true,
      friends: [
        1,
        0,
        2,
        3,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 5,
      grievances: false,
      public: false,
      private: false,
      friends: [
        2,
        0,
        1,
        3,
        4,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 6,
      grievances: true,
      public: false,
      private: false,
      friends: [
        0,
        1,
        2,
        3,
        4,
        5,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 7,
      grievances: true,
      public: true,
      private: false,
      friends: [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 8,
      grievances: true,
      public: false,
      private: true,
      friends: [
        5,
        2,
        0,
        1,
        3,
        4,
        6,
        7,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 9,
      grievances: true,
      public: true,
      private: false,
      friends: [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 2,
    },
    {
      id: 10,
      grievances: true,
      public: true,
      private: false,
      friends: [
        9,
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 11,
      grievances: false,
      public: false,
      private: false,
      friends: [
        1,
        0,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 12,
      grievances: false,
      public: true,
      private: true,
      friends: [
        11,
        1,
        0,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: ['P'],
      nResponses: 2,
    },
    {
      id: 13,
      grievances: true,
      public: true,
      private: false,
      friends: [
        4,
        1,
        0,
        2,
        3,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 14,
      grievances: false,
      public: false,
      private: true,
      friends: [23],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 15,
      grievances: true,
      public: true,
      private: true,
      friends: [
        7,
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10,
        11,
        12,
        13,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 2,
    },
    {
      id: 16,
      grievances: false,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 17,
      grievances: true,
      public: false,
      private: true,
      friends: [
        8,
        5,
        2,
        0,
        1,
        3,
        4,
        6,
        7,
        9,
        10,
        11,
        12,
        13,
        15,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 18,
      grievances: false,
      public: true,
      private: false,
      friends: [
        2,
        0,
        1,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 19,
      grievances: false,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 20,
      grievances: false,
      public: false,
      private: false,
      friends: [
        3,
        0,
        1,
        2,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 21,
      grievances: true,
      public: true,
      private: false,
      friends: [
        18,
        2,
        0,
        1,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        20,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 22,
      grievances: false,
      public: true,
      private: true,
      friends: [
        7,
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        24,
      ],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 23,
      grievances: true,
      public: false,
      private: false,
      friends: [14],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 24,
      grievances: true,
      public: true,
      private: false,
      friends: [
        3,
        0,
        1,
        2,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
      ],
      selectedFor: [],
      nResponses: 20,
    },
  ],
  // Medium sized friends networks
  [
    {
      id: 0,
      grievances: true,
      public: true,
      private: false,
      friends: [1, 3, 6, 9, 16, 17, 22],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 1,
      grievances: false,
      public: false,
      private: true,
      friends: [0, 3, 6, 9, 16, 17, 22],
      selectedFor: ['dream'],
      nResponses: 20,
    },
    {
      id: 2,
      grievances: true,
      public: false,
      private: true,
      friends: [4, 8, 13, 14, 15, 19],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 3,
      grievances: false,
      public: true,
      private: true,
      friends: [0, 1, 6, 9, 16, 17, 22],
      selectedFor: ['UM'],
      nResponses: 20,
    },
    {
      id: 4,
      grievances: true,
      public: false,
      private: true,
      friends: [2, 8, 13, 14, 15, 19],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 5,
      grievances: true,
      public: false,
      private: false,
      friends: [7, 10, 12],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 6,
      grievances: false,
      public: true,
      private: true,
      friends: [1, 0, 3, 9, 16, 17, 22],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 7,
      grievances: true,
      public: false,
      private: true,
      friends: [5, 10, 12],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 8,
      grievances: false,
      public: false,
      private: false,
      friends: [4, 2, 13, 14, 15, 19],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 9,
      grievances: true,
      public: false,
      private: false,
      friends: [3, 0, 1, 6, 16, 17, 22],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 10,
      grievances: false,
      public: false,
      private: true,
      friends: [7, 5, 12],
      selectedFor: [],
      nResponses: 0,
    },
    {
      id: 11,
      grievances: false,
      public: false,
      private: true,
      friends: [20],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 12,
      grievances: false,
      public: true,
      private: true,
      friends: [7, 5, 10],
      selectedFor: ['P'],
      nResponses: 3,
    },
    {
      id: 13,
      grievances: true,
      public: false,
      private: true,
      friends: [4, 2, 8, 14, 15, 19],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 14,
      grievances: true,
      public: true,
      private: true,
      friends: [4, 2, 8, 13, 15, 19],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 15,
      grievances: true,
      public: false,
      private: false,
      friends: [8, 4, 2, 13, 14, 19],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 16,
      grievances: true,
      public: true,
      private: true,
      friends: [3, 0, 1, 6, 9, 17, 22],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 17,
      grievances: true,
      public: true,
      private: true,
      friends: [16, 3, 0, 1, 6, 9, 22],
      selectedFor: [],
      nResponses: 2,
    },
    {
      id: 18,
      grievances: false,
      public: false,
      private: true,
      friends: [21],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 19,
      grievances: true,
      public: true,
      private: true,
      friends: [2, 4, 8, 13, 14, 15],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 20,
      grievances: true,
      public: false,
      private: false,
      friends: [11],
      selectedFor: [],
      nResponses: 1,
    },
    {
      id: 21,
      grievances: true,
      public: false,
      private: true,
      friends: [18],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 22,
      grievances: false,
      public: true,
      private: true,
      friends: [6, 1, 0, 3, 9, 16, 17],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 23,
      grievances: false,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 24,
      grievances: false,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
  ],
  // Small friends networks
  [
    {
      id: 0,
      grievances: false,
      public: false,
      private: false,
      friends: [3],
      selectedFor: [],
      nResponses: 0,
    },
    {
      id: 1,
      grievances: true,
      public: false,
      private: false,
      friends: [4, 14],
      selectedFor: ['dream'],
      nResponses: 1,
    },
    {
      id: 2,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 1,
    },
    {
      id: 3,
      grievances: true,
      public: true,
      private: false,
      friends: [0],
      selectedFor: ['UM'],
      nResponses: 0,
    },
    {
      id: 4,
      grievances: false,
      public: true,
      private: true,
      friends: [1, 14],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 5,
      grievances: false,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 6,
      grievances: false,
      public: true,
      private: true,
      friends: [7],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 7,
      grievances: true,
      public: false,
      private: false,
      friends: [6],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 8,
      grievances: false,
      public: false,
      private: false,
      friends: [16, 22],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 9,
      grievances: true,
      public: false,
      private: false,
      friends: [17, 18],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 10,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 11,
      grievances: false,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 12,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: ['P'],
      nResponses: 1,
    },
    {
      id: 13,
      grievances: true,
      public: false,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 14,
      grievances: false,
      public: true,
      private: true,
      friends: [4, 1],
      selectedFor: [],
      nResponses: 1,
    },
    {
      id: 15,
      grievances: true,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 16,
      grievances: true,
      public: false,
      private: true,
      friends: [8, 22],
      selectedFor: [],
      nResponses: 2,
    },
    {
      id: 17,
      grievances: true,
      public: true,
      private: true,
      friends: [9, 18],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 18,
      grievances: true,
      public: false,
      private: false,
      friends: [9, 17],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 19,
      grievances: false,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 20,
      grievances: true,
      public: false,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 21,
      grievances: true,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 22,
      grievances: false,
      public: false,
      private: false,
      friends: [8, 16],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 23,
      grievances: false,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 24,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
  ],
  // No friends networks
  [
    {
      id: 0,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 1,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: ['dream'],
      nResponses: 20,
    },
    {
      id: 2,
      grievances: true,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 3,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: ['UM'],
      nResponses: 2,
    },
    {
      id: 4,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 5,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 1,
    },
    {
      id: 6,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 7,
      grievances: false,
      public: false,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 8,
      grievances: false,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 9,
      grievances: false,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 0,
    },
    {
      id: 10,
      grievances: true,
      public: false,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 11,
      grievances: false,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 12,
      grievances: true,
      public: true,
      private: true,
      friends: [],
      selectedFor: ['P'],
      nResponses: 2,
    },
    {
      id: 13,
      grievances: false,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 14,
      grievances: false,
      public: false,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 15,
      grievances: false,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 1,
    },
    {
      id: 16,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 17,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 18,
      grievances: false,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 19,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 0,
    },
    {
      id: 20,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 21,
      grievances: false,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 0,
    },
    {
      id: 22,
      grievances: false,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 2,
    },
    {
      id: 23,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 24,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
  ],
]

export const deathList = [
  {
    id: 189,
    dateCreated: '2021-06-18T13:17:27.228Z',
    isSimulation: false,
    idc: 1,
    user: 203,
    deathForm: null,
    crossing: 17,
    userId: 203,
    crossingId: 17,
    idcWord: 'dehors',
  },
  {
    id: 191,
    dateCreated: '2021-06-18T13:30:39.911Z',
    isSimulation: false,
    idc: 2,
    user: 205,
    deathForm: {
      id: 150,
      firstname: null,
      lastname: null,
      gender: null,
      birthDate: null,
      birthPlace: null,
      afterLife: null,
      afterLifeMore: null,
      grievances: null,
      grievancesDetails: null,
      job: null,
      pet: null,
      petDetails: null,
      importantPeopleRoles: null,
      importantPeopleNames: null,
      crossingType: null,
      intimate: null,
      public: null,
      captcha: null,
      song: null,
      dream: null,
      dreamDetails: null,
      enemy: null,
      enemyDetails: null,
      remorse: null,
      remorseDetails: null,
      imageRights: null,
      iVoteFor: '4',
      eraseMyData: true,
      crossingDate: null,
      dateCreated: '2021-06-18T15:52:13.565Z',
      dateModified: null,
      filled: false,
    },
    crossing: 17,
    userId: 205,
    crossingId: 17,
    idcWord: 'manteau',
  },
  {
    id: 192,
    dateCreated: '2021-06-18T13:30:40.350Z',
    isSimulation: false,
    idc: 3,
    user: 206,
    deathForm: null,
    crossing: 17,
    userId: 206,
    crossingId: 17,
    idcWord: 'blouse',
  },
  {
    id: 193,
    dateCreated: '2021-06-18T13:30:40.769Z',
    isSimulation: false,
    idc: 4,
    user: 207,
    deathForm: null,
    crossing: 17,
    userId: 207,
    crossingId: 17,
    idcWord: 'stagiaire',
  },
  {
    id: 194,
    dateCreated: '2021-06-18T13:30:40.999Z',
    isSimulation: false,
    idc: 5,
    user: 208,
    deathForm: null,
    crossing: 17,
    userId: 208,
    crossingId: 17,
    idcWord: 'parcours',
  },
  {
    id: 195,
    dateCreated: '2021-06-18T13:30:41.430Z',
    isSimulation: false,
    idc: 6,
    user: 209,
    deathForm: {
      id: 153,
      firstname: null,
      lastname: null,
      gender: null,
      birthDate: null,
      birthPlace: null,
      afterLife: null,
      afterLifeMore: null,
      grievances: null,
      grievancesDetails: null,
      job: null,
      pet: null,
      petDetails: null,
      importantPeopleRoles: null,
      importantPeopleNames: null,
      crossingType: null,
      intimate: null,
      public: null,
      captcha: null,
      song: null,
      dream: null,
      dreamDetails: null,
      enemy: null,
      enemyDetails: null,
      remorse: null,
      remorseDetails: null,
      imageRights: null,
      iVoteFor: '4',
      eraseMyData: true,
      crossingDate: null,
      dateCreated: '2021-06-18T16:03:02.709Z',
      dateModified: null,
      filled: false,
    },
    crossing: 17,
    userId: 209,
    crossingId: 17,
    idcWord: 'autonomie',
  },
  {
    id: 196,
    dateCreated: '2021-06-18T13:30:41.710Z',
    isSimulation: false,
    idc: 7,
    user: 210,
    deathForm: null,
    crossing: 17,
    userId: 210,
    crossingId: 17,
    idcWord: 'attente',
  },
  {
    id: 197,
    dateCreated: '2021-06-18T13:30:41.989Z',
    isSimulation: false,
    idc: 8,
    user: 211,
    deathForm: {
      id: 151,
      firstname: null,
      lastname: null,
      gender: null,
      birthDate: null,
      birthPlace: null,
      afterLife: null,
      afterLifeMore: null,
      grievances: null,
      grievancesDetails: null,
      job: null,
      pet: null,
      petDetails: null,
      importantPeopleRoles: null,
      importantPeopleNames: null,
      crossingType: null,
      intimate: null,
      public: null,
      captcha: null,
      song: null,
      dream: null,
      dreamDetails: null,
      enemy: null,
      enemyDetails: null,
      remorse: null,
      remorseDetails: null,
      imageRights: null,
      iVoteFor: '2',
      eraseMyData: true,
      crossingDate: null,
      dateCreated: '2021-06-18T15:53:16.842Z',
      dateModified: null,
      filled: false,
    },
    crossing: 17,
    userId: 211,
    crossingId: 17,
    idcWord: 'cabine',
  },
  {
    id: 198,
    dateCreated: '2021-06-18T13:30:42.229Z',
    isSimulation: false,
    idc: 9,
    user: 212,
    deathForm: null,
    crossing: 17,
    userId: 212,
    crossingId: 17,
    idcWord: 'espace',
  },
  {
    id: 199,
    dateCreated: '2021-06-18T13:30:42.603Z',
    isSimulation: false,
    idc: 10,
    user: 213,
    deathForm: null,
    crossing: 17,
    userId: 213,
    crossingId: 17,
    idcWord: 'manger',
  },
  {
    id: 200,
    dateCreated: '2021-06-18T13:30:42.948Z',
    isSimulation: false,
    idc: 11,
    user: 182,
    deathForm: {
      id: 147,
      firstname: 'Camille',
      lastname: 'Gomette',
      gender: 'M',
      birthDate: '1983-12-31T23:00:00.000Z',
      birthPlace: '{"latitude":null,"longitude":null}',
      afterLife: 'MÉTEMPSYCOSE',
      afterLifeMore: null,
      grievances: true,
      grievancesDetails:
        "Je n'aime pas les gens qui disent \"Au jour d'aujourd'hui \"",
      job: 'Boucher/Charcutier',
      pet: null,
      petDetails: null,
      importantPeopleRoles: ['LONG_LOST_FRIEND', 'LONG_LOST_FRIEND', 'ENEMY'],
      importantPeopleNames: ['Riri', 'Fifi', 'Loulou'],
      crossingType: 'AMAZING',
      intimate: 'COURAGE',
      public: 'COURAGE',
      captcha: 'Une Buse',
      song: 'Chikita',
      dream: false,
      dreamDetails: null,
      enemy: false,
      enemyDetails: null,
      remorse: false,
      remorseDetails: null,
      imageRights: false,
      iVoteFor: null,
      eraseMyData: null,
      crossingDate: '2021-06-18T15:30:00.000Z',
      dateCreated: '2021-06-17T10:45:32.335Z',
      dateModified: null,
      filled: false,
    },
    crossing: 17,
    userId: 182,
    crossingId: 17,
    idcWord: 'banane',
  },
  {
    id: 201,
    dateCreated: '2021-06-18T13:30:43.249Z',
    isSimulation: false,
    idc: 12,
    user: 215,
    deathForm: null,
    crossing: 17,
    userId: 215,
    crossingId: 17,
    idcWord: 'ordinateur',
  },
  {
    id: 202,
    dateCreated: '2021-06-18T13:30:43.913Z',
    isSimulation: false,
    idc: 13,
    user: 193,
    deathForm: {
      id: 149,
      firstname: 'Clémence',
      lastname: 'Gueidan',
      gender: 'OTHER',
      birthDate: '1984-11-30T23:00:00.000Z',
      birthPlace: '{"latitude":null,"longitude":null}',
      afterLife: 'CEPM',
      afterLifeMore: null,
      grievances: false,
      grievancesDetails: null,
      job: 'Designer',
      pet: null,
      petDetails: null,
      importantPeopleRoles: ['SOULMATE', 'PARTNER', 'FRIEND'],
      importantPeopleNames: ['Marie', 'Olivier', 'Pierrick'],
      crossingType: 'EXCITING',
      intimate: 'COURAGE',
      public: 'COURAGE',
      captcha: 'Un Candélabre',
      song: 'Could have been me - The Struts',
      dream: false,
      dreamDetails: null,
      enemy: false,
      enemyDetails: null,
      remorse: false,
      remorseDetails: null,
      imageRights: true,
      iVoteFor: '7',
      eraseMyData: false,
      crossingDate: '2021-06-18T15:30:00.000Z',
      dateCreated: '2021-06-17T19:35:36.883Z',
      dateModified: null,
      filled: false,
    },
    crossing: 17,
    userId: 193,
    crossingId: 17,
    idcWord: 'tranquillement',
  },
  {
    id: 203,
    dateCreated: '2021-06-18T13:30:44.112Z',
    isSimulation: false,
    idc: 14,
    user: 217,
    deathForm: null,
    crossing: 17,
    userId: 217,
    crossingId: 17,
    idcWord: 'bataille',
  },
  {
    id: 204,
    dateCreated: '2021-06-18T13:30:44.389Z',
    isSimulation: false,
    idc: 15,
    user: 218,
    deathForm: null,
    crossing: 17,
    userId: 218,
    crossingId: 17,
    idcWord: 'ensemble',
  },
  {
    id: 205,
    dateCreated: '2021-06-18T13:30:44.649Z',
    isSimulation: false,
    idc: 16,
    user: 219,
    deathForm: null,
    crossing: 17,
    userId: 219,
    crossingId: 17,
    idcWord: 'toilette',
  },
  {
    id: 206,
    dateCreated: '2021-06-18T13:30:44.912Z',
    isSimulation: false,
    idc: 17,
    user: 220,
    deathForm: null,
    crossing: 17,
    userId: 220,
    crossingId: 17,
    idcWord: 'dents',
  },
  {
    id: 207,
    dateCreated: '2021-06-18T13:30:45.149Z',
    isSimulation: false,
    idc: 18,
    user: 221,
    deathForm: null,
    crossing: 17,
    userId: 221,
    crossingId: 17,
    idcWord: 'coiffe',
  },
  {
    id: 208,
    dateCreated: '2021-06-18T13:30:45.373Z',
    isSimulation: false,
    idc: 19,
    user: 222,
    deathForm: null,
    crossing: 17,
    userId: 222,
    crossingId: 17,
    idcWord: 'visage',
  },
  {
    id: 209,
    dateCreated: '2021-06-18T13:30:45.608Z',
    isSimulation: false,
    idc: 20,
    user: 223,
    deathForm: null,
    crossing: 17,
    userId: 223,
    crossingId: 17,
    idcWord: 'maquillage',
  },
  {
    id: 210,
    dateCreated: '2021-06-18T13:30:45.889Z',
    isSimulation: false,
    idc: 21,
    user: 224,
    deathForm: null,
    crossing: 17,
    userId: 224,
    crossingId: 17,
    idcWord: 'beaucoup',
  },
  {
    id: 211,
    dateCreated: '2021-06-18T13:30:46.372Z',
    isSimulation: false,
    idc: 22,
    user: 202,
    deathForm: {
      id: 146,
      firstname: 'Anne Teresa',
      lastname: 'Piel',
      gender: 'F',
      birthDate: '1991-08-31T22:00:00.000Z',
      birthPlace: '{"latitude":null,"longitude":null}',
      afterLife: 'PARADISE',
      afterLifeMore: null,
      grievances: false,
      grievancesDetails: null,
      job: 'Responsable de production',
      pet: null,
      petDetails: null,
      importantPeopleRoles: ['', '', ''],
      importantPeopleNames: ['Christian Piel', 'Samuel Piel', 'Solange Piel'],
      crossingType: 'HAPPY',
      intimate: 'COURAGE',
      public: 'COURAGE',
      captcha: 'Un Candélabre',
      song: 'Pookie, Aya Nakamura',
      dream: true,
      dreamDetails:
        "Un rêve récent, j'ai rêvé que j'étais une colocation avec Benjamin Biolay et un ami à lui. C'était très simple, sans chichis. Et il y avait beaucoup de stars qui passaient à la maison. Et là je me suis dis que c'était bizarre et je me suis réveillée",
      enemy: false,
      enemyDetails: null,
      remorse: false,
      remorseDetails: null,
      imageRights: true,
      iVoteFor: null,
      eraseMyData: null,
      crossingDate: '2021-06-18T15:30:00.000Z',
      dateCreated: '2021-06-18T09:51:03.358Z',
      dateModified: null,
      filled: false,
    },
    crossing: 17,
    userId: 202,
    crossingId: 17,
    idcWord: 'trop',
  },
  {
    id: 212,
    dateCreated: '2021-06-18T13:30:46.609Z',
    isSimulation: false,
    idc: 23,
    user: 226,
    deathForm: null,
    crossing: 17,
    userId: 226,
    crossingId: 17,
    idcWord: 'doute',
  },
  {
    id: 213,
    dateCreated: '2021-06-18T13:30:46.847Z',
    isSimulation: false,
    idc: 24,
    user: 227,
    deathForm: null,
    crossing: 17,
    userId: 227,
    crossingId: 17,
    idcWord: 'uniforme',
  },
  {
    id: 214,
    dateCreated: '2021-06-18T13:30:47.069Z',
    isSimulation: false,
    idc: 25,
    user: 241,
    deathForm: {
      id: 148,
      firstname: 'Lilas',
      lastname: 'Rousseau',
      gender: 'F',
      birthDate: '1995-04-30T22:00:00.000Z',
      birthPlace: '{"latitude":null,"longitude":null}',
      afterLife: 'TRANSMIGRATION',
      afterLifeMore: null,
      grievances: true,
      grievancesDetails: '',
      job: 'Stagiaire en production au 104 ',
      pet: true,
      petDetails: 'Mon chien Gus et ma chienne Blues',
      importantPeopleRoles: ['PARTNER', 'FAMILY', 'FRIEND'],
      importantPeopleNames: [
        'Gabriel Sauvageot ',
        'Sophie Paul Lucas',
        'Marie Marge Julie Sara ',
      ],
      crossingType: 'FUNNY',
      intimate: 'COURAGE',
      public: 'COWARDICE',
      captcha: 'Un Candélabre',
      song: 'Prince - kiss',
      dream: true,
      dreamDetails: 'On me poursuit ',
      enemy: false,
      enemyDetails: null,
      remorse: true,
      remorseDetails:
        'Il y a 5 ans, un mec m’a violé et j’ai été paralysée par la peur. J’aurai voulu crier me débattre. Mais j’ai pas pu. Relou les années qui ont suivis derrière ',
      imageRights: true,
      iVoteFor: null,
      eraseMyData: null,
      crossingDate: '2021-06-18T15:30:00.000Z',
      dateCreated: '2021-06-18T15:15:28.937Z',
      dateModified: null,
      filled: false,
    },
    crossing: 17,
    userId: 241,
    crossingId: 17,
    idcWord: 'retard',
  },
  {
    id: 215,
    dateCreated: '2021-06-18T13:30:47.268Z',
    isSimulation: false,
    idc: 26,
    user: 229,
    deathForm: {
      id: 152,
      firstname: null,
      lastname: null,
      gender: null,
      birthDate: null,
      birthPlace: null,
      afterLife: null,
      afterLifeMore: null,
      grievances: null,
      grievancesDetails: null,
      job: null,
      pet: null,
      petDetails: null,
      importantPeopleRoles: null,
      importantPeopleNames: null,
      crossingType: null,
      intimate: null,
      public: null,
      captcha: null,
      song: null,
      dream: null,
      dreamDetails: null,
      enemy: null,
      enemyDetails: null,
      remorse: null,
      remorseDetails: null,
      imageRights: null,
      iVoteFor: '3',
      eraseMyData: false,
      crossingDate: null,
      dateCreated: '2021-06-18T15:54:11.451Z',
      dateModified: null,
      filled: false,
    },
    crossing: 17,
    userId: 229,
    crossingId: 17,
    idcWord: 'silence',
  },
  {
    id: 216,
    dateCreated: '2021-06-18T13:30:47.509Z',
    isSimulation: false,
    idc: 27,
    user: 230,
    deathForm: null,
    crossing: 17,
    userId: 230,
    crossingId: 17,
    idcWord: 'revues',
  },
  {
    id: 217,
    dateCreated: '2021-06-18T13:30:47.780Z',
    isSimulation: false,
    idc: 28,
    user: 231,
    deathForm: null,
    crossing: 17,
    userId: 231,
    crossingId: 17,
    idcWord: 'climatisation',
  },
  {
    id: 218,
    dateCreated: '2021-06-18T13:30:48.009Z',
    isSimulation: false,
    idc: 29,
    user: 188,
    deathForm: {
      id: 144,
      firstname: 'LISA',
      lastname: 'GALAIS',
      gender: 'F',
      birthDate: '1997-04-30T22:00:00.000Z',
      birthPlace: '{"latitude":null,"longitude":null}',
      afterLife: 'REINCARNATION',
      afterLifeMore: null,
      grievances: false,
      grievancesDetails: null,
      job: 'Assistante de production – Accueil des équipes artistiques ',
      pet: null,
      petDetails: null,
      importantPeopleRoles: ['FAMILY', 'FAMILY', 'FAMILY'],
      importantPeopleNames: ['ma mère', 'Ma grande soeur', 'Ma petite soeur'],
      crossingType: 'HILARIOUS',
      intimate: 'COURAGE',
      public: 'COURAGE',
      captcha: 'Un Candélabre',
      song: 'Pretty Face - Soley',
      dream: true,
      dreamDetails: 'Chute dans le vide',
      enemy: false,
      enemyDetails: null,
      remorse: false,
      remorseDetails: null,
      imageRights: true,
      iVoteFor: null,
      eraseMyData: null,
      crossingDate: '2021-06-18T15:30:00.000Z',
      dateCreated: '2021-06-17T14:44:56.259Z',
      dateModified: null,
      filled: false,
    },
    crossing: 17,
    userId: 188,
    crossingId: 17,
    idcWord: 'annonce',
  },
  {
    id: 219,
    dateCreated: '2021-06-18T13:30:48.228Z',
    isSimulation: false,
    idc: 30,
    user: 233,
    deathForm: null,
    crossing: 17,
    userId: 233,
    crossingId: 17,
    idcWord: 'respect',
  },
  {
    id: 220,
    dateCreated: '2021-06-18T13:30:48.518Z',
    isSimulation: false,
    idc: 31,
    user: 234,
    deathForm: null,
    crossing: 17,
    userId: 234,
    crossingId: 17,
    idcWord: 'environnement',
  },
  {
    id: 221,
    dateCreated: '2021-06-18T13:30:48.730Z',
    isSimulation: false,
    idc: 32,
    user: 235,
    deathForm: null,
    crossing: 17,
    userId: 235,
    crossingId: 17,
    idcWord: 'pourquoi',
  },
  {
    id: 222,
    dateCreated: '2021-06-18T13:30:49.330Z',
    isSimulation: false,
    idc: 33,
    user: 236,
    deathForm: null,
    crossing: 17,
    userId: 236,
    crossingId: 17,
    idcWord: 'dossier',
  },
  {
    id: 223,
    dateCreated: '2021-06-18T13:30:49.708Z',
    isSimulation: false,
    idc: 34,
    user: 237,
    deathForm: null,
    crossing: 17,
    userId: 237,
    crossingId: 17,
    idcWord: 'continu',
  },
  {
    id: 225,
    dateCreated: '2021-06-18T14:50:13.895Z',
    isSimulation: false,
    idc: 35,
    user: 239,
    deathForm: null,
    crossing: 17,
    userId: 239,
    crossingId: 17,
    idcWord: 'cadre',
  },
  {
    id: 226,
    dateCreated: '2021-06-18T14:50:22.574Z',
    isSimulation: false,
    idc: 36,
    user: 240,
    deathForm: null,
    crossing: 17,
    userId: 240,
    crossingId: 17,
    idcWord: 'suite',
  },
]
