export const groupData = [
  // Big friends networks
  [
    {
      id: 0,
      grievances: true,
      public: false,
      private: false,
      friends: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 1,
      grievances: true,
      public: false,
      private: true,
      friends: [
        0,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: ['dream'],
      nResponses: 20,
    },
    {
      id: 2,
      grievances: false,
      public: true,
      private: true,
      friends: [
        0,
        1,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 2,
    },
    {
      id: 3,
      grievances: false,
      public: true,
      private: false,
      friends: [
        0,
        1,
        2,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: ['UM'],
      nResponses: 20,
    },
    {
      id: 4,
      grievances: false,
      public: false,
      private: true,
      friends: [
        1,
        0,
        2,
        3,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 5,
      grievances: false,
      public: false,
      private: false,
      friends: [
        2,
        0,
        1,
        3,
        4,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 6,
      grievances: true,
      public: false,
      private: false,
      friends: [
        0,
        1,
        2,
        3,
        4,
        5,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 7,
      grievances: true,
      public: true,
      private: false,
      friends: [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 8,
      grievances: true,
      public: false,
      private: true,
      friends: [
        5,
        2,
        0,
        1,
        3,
        4,
        6,
        7,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 9,
      grievances: true,
      public: true,
      private: false,
      friends: [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 2,
    },
    {
      id: 10,
      grievances: true,
      public: true,
      private: false,
      friends: [
        9,
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 11,
      grievances: false,
      public: false,
      private: false,
      friends: [
        1,
        0,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 12,
      grievances: false,
      public: true,
      private: true,
      friends: [
        11,
        1,
        0,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: ['P'],
      nResponses: 2,
    },
    {
      id: 13,
      grievances: true,
      public: true,
      private: false,
      friends: [
        4,
        1,
        0,
        2,
        3,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        15,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 14,
      grievances: false,
      public: false,
      private: true,
      friends: [23],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 15,
      grievances: true,
      public: true,
      private: true,
      friends: [
        7,
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10,
        11,
        12,
        13,
        17,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 2,
    },
    {
      id: 16,
      grievances: false,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 17,
      grievances: true,
      public: false,
      private: true,
      friends: [
        8,
        5,
        2,
        0,
        1,
        3,
        4,
        6,
        7,
        9,
        10,
        11,
        12,
        13,
        15,
        18,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 18,
      grievances: false,
      public: true,
      private: false,
      friends: [
        2,
        0,
        1,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        20,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 19,
      grievances: false,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 20,
      grievances: false,
      public: false,
      private: false,
      friends: [
        3,
        0,
        1,
        2,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        21,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 21,
      grievances: true,
      public: true,
      private: false,
      friends: [
        18,
        2,
        0,
        1,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        20,
        22,
        24,
      ],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 22,
      grievances: false,
      public: true,
      private: true,
      friends: [
        7,
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        24,
      ],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 23,
      grievances: true,
      public: false,
      private: false,
      friends: [14],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 24,
      grievances: true,
      public: true,
      private: false,
      friends: [
        3,
        0,
        1,
        2,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        17,
        18,
        20,
        21,
        22,
      ],
      selectedFor: [],
      nResponses: 20,
    },
  ],
  // Medium sized friends networks
  [
    {
      id: 0,
      grievances: true,
      public: true,
      private: false,
      friends: [1, 3, 6, 9, 16, 17, 22],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 1,
      grievances: false,
      public: false,
      private: true,
      friends: [0, 3, 6, 9, 16, 17, 22],
      selectedFor: ['dream'],
      nResponses: 20,
    },
    {
      id: 2,
      grievances: true,
      public: false,
      private: true,
      friends: [4, 8, 13, 14, 15, 19],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 3,
      grievances: false,
      public: true,
      private: true,
      friends: [0, 1, 6, 9, 16, 17, 22],
      selectedFor: ['UM'],
      nResponses: 20,
    },
    {
      id: 4,
      grievances: true,
      public: false,
      private: true,
      friends: [2, 8, 13, 14, 15, 19],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 5,
      grievances: true,
      public: false,
      private: false,
      friends: [7, 10, 12],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 6,
      grievances: false,
      public: true,
      private: true,
      friends: [1, 0, 3, 9, 16, 17, 22],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 7,
      grievances: true,
      public: false,
      private: true,
      friends: [5, 10, 12],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 8,
      grievances: false,
      public: false,
      private: false,
      friends: [4, 2, 13, 14, 15, 19],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 9,
      grievances: true,
      public: false,
      private: false,
      friends: [3, 0, 1, 6, 16, 17, 22],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 10,
      grievances: false,
      public: false,
      private: true,
      friends: [7, 5, 12],
      selectedFor: [],
      nResponses: 0,
    },
    {
      id: 11,
      grievances: false,
      public: false,
      private: true,
      friends: [20],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 12,
      grievances: false,
      public: true,
      private: true,
      friends: [7, 5, 10],
      selectedFor: ['P'],
      nResponses: 3,
    },
    {
      id: 13,
      grievances: true,
      public: false,
      private: true,
      friends: [4, 2, 8, 14, 15, 19],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 14,
      grievances: true,
      public: true,
      private: true,
      friends: [4, 2, 8, 13, 15, 19],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 15,
      grievances: true,
      public: false,
      private: false,
      friends: [8, 4, 2, 13, 14, 19],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 16,
      grievances: true,
      public: true,
      private: true,
      friends: [3, 0, 1, 6, 9, 17, 22],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 17,
      grievances: true,
      public: true,
      private: true,
      friends: [16, 3, 0, 1, 6, 9, 22],
      selectedFor: [],
      nResponses: 2,
    },
    {
      id: 18,
      grievances: false,
      public: false,
      private: true,
      friends: [21],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 19,
      grievances: true,
      public: true,
      private: true,
      friends: [2, 4, 8, 13, 14, 15],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 20,
      grievances: true,
      public: false,
      private: false,
      friends: [11],
      selectedFor: [],
      nResponses: 1,
    },
    {
      id: 21,
      grievances: true,
      public: false,
      private: true,
      friends: [18],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 22,
      grievances: false,
      public: true,
      private: true,
      friends: [6, 1, 0, 3, 9, 16, 17],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 23,
      grievances: false,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 24,
      grievances: false,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
  ],
  // Small friends networks
  [
    {
      id: 0,
      grievances: false,
      public: false,
      private: false,
      friends: [3],
      selectedFor: [],
      nResponses: 0,
    },
    {
      id: 1,
      grievances: true,
      public: false,
      private: false,
      friends: [4, 14],
      selectedFor: ['dream'],
      nResponses: 1,
    },
    {
      id: 2,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 1,
    },
    {
      id: 3,
      grievances: true,
      public: true,
      private: false,
      friends: [0],
      selectedFor: ['UM'],
      nResponses: 0,
    },
    {
      id: 4,
      grievances: false,
      public: true,
      private: true,
      friends: [1, 14],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 5,
      grievances: false,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 6,
      grievances: false,
      public: true,
      private: true,
      friends: [7],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 7,
      grievances: true,
      public: false,
      private: false,
      friends: [6],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 8,
      grievances: false,
      public: false,
      private: false,
      friends: [16, 22],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 9,
      grievances: true,
      public: false,
      private: false,
      friends: [17, 18],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 10,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 11,
      grievances: false,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 12,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: ['P'],
      nResponses: 1,
    },
    {
      id: 13,
      grievances: true,
      public: false,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 14,
      grievances: false,
      public: true,
      private: true,
      friends: [4, 1],
      selectedFor: [],
      nResponses: 1,
    },
    {
      id: 15,
      grievances: true,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 16,
      grievances: true,
      public: false,
      private: true,
      friends: [8, 22],
      selectedFor: [],
      nResponses: 2,
    },
    {
      id: 17,
      grievances: true,
      public: true,
      private: true,
      friends: [9, 18],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 18,
      grievances: true,
      public: false,
      private: false,
      friends: [9, 17],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 19,
      grievances: false,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 20,
      grievances: true,
      public: false,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 21,
      grievances: true,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 22,
      grievances: false,
      public: false,
      private: false,
      friends: [8, 16],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 23,
      grievances: false,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 24,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
  ],
  // No friends networks
  [
    {
      id: 0,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 1,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: ['dream'],
      nResponses: 20,
    },
    {
      id: 2,
      grievances: true,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 3,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: ['UM'],
      nResponses: 2,
    },
    {
      id: 4,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 5,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 1,
    },
    {
      id: 6,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 7,
      grievances: false,
      public: false,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 4,
    },
    {
      id: 8,
      grievances: false,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 9,
      grievances: false,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 0,
    },
    {
      id: 10,
      grievances: true,
      public: false,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 11,
      grievances: false,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 12,
      grievances: true,
      public: true,
      private: true,
      friends: [],
      selectedFor: ['P'],
      nResponses: 2,
    },
    {
      id: 13,
      grievances: false,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 14,
      grievances: false,
      public: false,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 15,
      grievances: false,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 1,
    },
    {
      id: 16,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 3,
    },
    {
      id: 17,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 18,
      grievances: false,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 19,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 0,
    },
    {
      id: 20,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 21,
      grievances: false,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 0,
    },
    {
      id: 22,
      grievances: false,
      public: true,
      private: true,
      friends: [],
      selectedFor: [],
      nResponses: 2,
    },
    {
      id: 23,
      grievances: true,
      public: true,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
    {
      id: 24,
      grievances: true,
      public: false,
      private: false,
      friends: [],
      selectedFor: [],
      nResponses: 20,
    },
  ],
]
